apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
        name: l2-bridge
spec:
        config: '{
                "cniVersion": "0.3.1",
                "name": "l2-bridge",
                "type": "bridge",
                "bridge": "l2-bridge",
                "ipam": {
                        "type": "host-local",
                        "subnet": "172.31.1.0/24"
                }
        }'

