apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
        name: l3-bridge
spec:
        config: '{
                "cniVersion": "0.3.1",
                "name": "l3-bridge",
                "type": "bridge",
                "bridge": "l3-bridge",
                "isGateway": true,
                "forceAddress": true,
                "ipam": {
                        "type": "host-local",
                        "subnet": "172.16.0.0/24"
                }
        }'

