apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
        name: macvlan
spec:
        config: '{
                "cniVersion": "0.3.1",
                "name": "macvlan",
                "type": "macvlan",
                "master": "eth0",
                "ipam": {
                        "type": "dhcp"
                }
        }'
        # dhcp in ipam above requires that the cni dhcp daemon is running
        # this is located in /opt/cni/bin, cd there and: #> sudo ./dhcp daemon
        # Easier is to run a daemonset to do this, see:
        #   https://github.com/georgenicoll/reference-deployment/blob/master/multus-dhcp/dhcp-daemonset-arm64.yml

