apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
        name: macvlan
spec:
        config: '{
                "cniVersion": "0.3.1",
                "name": "macvlan",
                "type": "macvlan",
                "master": "eth0",
                "ipam": {
                        "type": "dhcp"
                }
        }'
        # dhcp in ipam above requires that the cni dhcp daemon is running
        # this is located in /opt/cni/bin, cd there and: #> sudo ./dhcp daemon
        # TODO: work out how to run this as a DaemonSet

