apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
        name: ipvlan
spec:
        config: '{
                "cniVersion": "0.3.1",
                "name": "cni-ipvlan",
                "type": "ipvlan",
                "master": "eth0",
                "ipam": {
                        "type": "host-local",
                        "subnet": "10.3.2.0/24"
                }
        }'

