apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
        name: host-bridge
spec:
        config: '{
                "cniVersion": "0.3.1",
                "name": "host-bridge",
                "type": "bridge",
                "bridge": "cni-bridge",
                "isDefaultGateway": true,
                "forceAddress": false,
                "ipMasq": true,
                "hairpinMode": true,
                "ipam": {
                        "type": "host-local",
                        "ranges": [
                                [
                                        {
                                                "subnet": "172.16.5.0/24"
                                        }
                                ]
                        ]
                }
        }'

